# Generated by Django 4.1.2 on 2022-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва рецепту')),
                ('description', models.CharField(max_length=100, verbose_name='Опис рецепту')),
                ('photo', models.ImageField(upload_to='uploads/', verbose_name='Фото рецепту')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепти',
            },
        ),
    ]
