# Generated by Django 4.1.2 on 2022-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Поточний стан користувача'),
        ),
    ]
