# Generated by Django 4.1.2 on 2022-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_telegramuser_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20, verbose_name='Айді користувача в телеграмі')),
                ('state', models.CharField(max_length=20, verbose_name='Стан користувача')),
            ],
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='state',
        ),
    ]
