# Generated by Django 4.1.2 on 2022-10-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я користувача в телеграмі")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище користувача в телеграмі')),
                ('username', models.CharField(max_length=100, verbose_name='Юзернейм користувача в телеграмі')),
                ('questioned_name', models.CharField(max_length=100, verbose_name="Ім'я користувача з анкети")),
                ('sex', models.CharField(max_length=100, verbose_name='Стать користувача в телеграмі')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
