# Generated by Django 4.1.2 on 2022-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(default='', max_length=100, verbose_name='Айді користувача в телеграмі'),
            preserve_default=False,
        ),
    ]
